import styles from '../Disclaimers.module.scss';

const PrivacyPolicy = () => {
  return (
    <div className={styles['container']}>
      <div className={styles['title']}>
        <h1>
          FLX Operating, LLC
          <br />
          Privacy Policy
        </h1>
        <h2>Effective Date: May 14, 2018</h2>
      </div>

      <div className={styles['wrapper']}>
        <p>
          Welcome to the felixhomes.com website (“Website”), which is owned and
          operated by FLX Operating, LLC (together with its related, affiliated,
          subsidiary, and/or parent companies, “FELIX”). This Website has been
          created to provide information about FELIX and the services it offers
          to you (“You” or “Your”). FELIX values Your privacy and protection of
          Your sensitive personal information. This Privacy Policy (“Privacy
          Policy”) outlines what information FELIX collects from You through the
          Website and how that information is used. Subject to the limited
          exceptions set forth herein, FELIX will only keep information that You
          submit through the Website for its own internal use.
        </p>

        <h2>REVISIONS TO THE POLICY</h2>

        <p>
          By viewing, accessing, or using the Website, You agree to this Privacy
          Policy and accept all terms and conditions without modification. Any
          offer by You to modify the terms of this Privacy Policy is expressly
          rejected. FELIX reserves the right to revise, change, amend, alter,
          modify or update (collectively, “Update”) this Privacy Policy and its
          other policies and agreements at any time and in any manner without
          notice to You. You are responsible for periodically checking for any
          Updates of this Privacy Policy by re-visiting the Website and using
          the “refresh” button on the Your browser. Any Updates supersede any
          prior versions immediately upon posting on the Website.
        </p>

        <p>
          IF YOU DO NOT AGREE TO THE TERMS OF THIS PRIVACY POLICY, OR ANY
          UPDATES HERETO, YOUR SOLE REMEDY IS TO NOT USE THE WEBSITE AND ANY
          SERVICES OFFERED BY FELIX.
        </p>

        <h2>INFORMATION COLLECTED</h2>

        <p>
          FELIX collects personally identifiable information (“Personal
          Information”) from You when You voluntarily provide such information,
          such as when You contact felix and/or submit an Inquiry (as defined
          below) including, without limitation, Your email address and/or other
          financial information regarding Your home, register with the Website
          and/or register for any of the services offered by FELIX. By
          voluntarily providing FELIX with Personal Information, You are
          consenting to FELIX’s use of it in accordance with this Privacy
          Policy.
        </p>

        <p>
          FELIX will retain the Personal Information as long as Your account is
          active or as needed to provide You with any services requested by You.
          FELIX will retain and use Your information as necessary to comply with
          FELIX’s legal obligations, resolve disputes, and enforce FELIX’s
          agreements.
        </p>

        <p>
          In addition, the Website may collect data that cannot be traced back
          to a specific individual (“Anonymous Information”). For example, FELIX
          may be able to keep track of your geographic location including,
          without limitation, through the use of Google Maps and other web
          mapping services (which are governed by Google’s privacy policy and
          other website agreements that You are solely responsible for
          reviewing). By way of another example, FELIX may be able to keep count
          of how many users have viewed the Website and specific content
          therein, keywords utilized to find the Website, or keywords utilized
          to search within the Website, but this information does not
          necessarily include information regarding users’ names, street
          addresses, telephone numbers or email addresses. In that regard, just
          by virtue of accessing, viewing, or using the Website, Anonymous
          Information will be collected by FELIX.
        </p>

        <p>
          In addition and without limitation, the Website uses Google Analytics,
          a web analytics service provided by Google, Inc. (“Google”). Google
          Analytics may utilize “cookies” to help analyze how Users use the
          Website. The information generated by the cookie about the Your use of
          the Website (including, without limitation, the Your IP address) may
          be transmitted and stored by Google on its servers. Google may use
          this information for various reasons, as identified in more detail on
          Google’s terms of service. You shall review Google’s terms of service
          for more information in this regard.
        </p>

        <p>
          In addition, the Website may use browser cookies to collect Anonymous
          Information. The Website may also incorporate web beacons or similar
          tracking technologies to allow FELIX to track how the Website is used.
          Such technologies are used to collect Anonymous Information, e.g. the
          name of Your internet service provider, the IP address of Your
          computer, Your browser software and operating system, the identity of
          any linked-form or linked-to website, and other similar information.
        </p>

        <p>
          FELIX may combine Your Anonymous Information with Your Personal
          Information and/or similar information collected from other users to
          help improve the Website and FELIX’s products and services.
        </p>

        <p>
          This Privacy Policy shall not apply to any unsolicited information You
          provide to FELIX including, without limitation, information posted to
          any public areas of the Website such as the blogs (“Unsolicited
          Information”). All Unsolicited Information shall be deemed to be
          non-confidential and FELIX shall be free to reproduce, use, disclose
          and distribute such Unsolicited Information to others without
          limitation or attribution.
        </p>

        <h2>INQUIRY</h2>

        <p>
          You may submit inquiries, feedback, comments, or other content
          (collectively, an “Inquiry”) to FELIX through the Website. You
          acknowledge and agree that by sending an Inquiry, Your personal
          information and/or any other information You supply, may be visible to
          third parties. You shall not share any information in Your Inquiry
          that You are not prepared to be public or to otherwise share with such
          other third parties. In that regard, You specifically acknowledge that
          FELIX has not implemented any security protocols in connection with
          maintaining the confidentiality of any information included in an
          Inquiry. In that regard, Your disclosure of same is at Your own risk.
          Moreover, Your Inquiry may be available for review by FELIX and/or
          other vendors, suppliers, contractors, and employees of FELIX.
          Moreover, FELIX may, from time to time, use third-party email servers
          to send and track receipt of the Inquiries, and analyze the pattern of
          inquiry activities via these third-party tracking systems.
        </p>

        <p>
          All submissions of content, including without limitation, an Inquiry
          sent to FELIX, are accepted solely in accordance with and governed by,
          the Website’s Terms of Use and other Website policies.
        </p>

        <h2>THIRD PARTY ADVERTISERS AND LINKS TO THIRD PARTY WEBSITES</h2>

        <p>
          The Website may include advertisements and listings from third-party
          companies, which may include links to third-party websites. The
          advertisements placed by these companies are not affiliated, owned,
          maintained, or updated by FELIX. If You visit the websites of these
          third parties, You do so at Your own risk. In addition and without
          limitation, such third-party websites may use cookies and/or request
          and collect Your personal information. FELIX does not know of the
          policies of these independent third parties and is not responsible for
          the information collected or how the information is used by any third
          parties. FELIX also cannot confirm or in any way guarantee the
          accuracy of the information provided by those third parties on their
          websites. FELIX strongly recommends that You read and review the
          privacy and other policies of any other third-party websites that You
          may view.
        </p>

        <h2>INFORMATION SHARING</h2>

        <p>
          FELIX uses the Personal Information You provide in a manner that is
          consistent with this Privacy Policy. If You provide Personal
          Information for a certain reason, FELIX may use the Personal
          Information in connection with the reason for which it is provided. By
          way of example, if You provide Personal Information in order to obtain
          services from FELIX, FELIX will use the Personal Information to
          determine if You qualify for such services and to provide such
          services to You.
        </p>

        <p>
          Except as otherwise provided in this Privacy Policy and/or any other
          agreement binding on You, FELIX will not intentionally distribute,
          rent or sell any information collected from You to third parties
          without your permission. FELIX may share any information collected
          from You, as set forth herein, amongst its parent companies,
          subsidiaries, affiliates, and other related entities and related
          websites. FELIX may be required by law enforcement or judicial
          authorities to provide Your Personal Information to the appropriate
          governmental authorities. If FELIX receives a request from law
          enforcement or judicial authorities or is otherwise required by law to
          reveal Your Personal Information, it reserves the right to provide the
          requested information.
        </p>

        <p>
          FELIX may use Your Personal Information and Anonymous Information to
          help us improve the content and functionality of the Website and/or
          any services offered by FELIX, to better understand FELIX’s users, and
          to improve any services offered by FELIX. FELIX may also contact You
          in the future to tell You about services and/or products that FELIX
          believes will be of interest to You. If FELIX does so, each marketing
          communication FELIX sends You will contain instructions permitting You
          to “opt-out” of receiving future marketing communications. In
          addition, if at any time, You wish not to receive any future marketing
          communications or You wish to have Your name deleted from FELIX’s
          mailing lists, please contact FELIX at: contact@felixhomes.com. If
          FELIX intends on using any Personal Information in any manner that is
          not consistent with this Privacy Policy, You will be informed of such
          anticipated use prior to or at the time at which the Personal
          Information is collected.
        </p>

        <h2>SECURITY PROCEDURES</h2>

        <p>
          FELIX undertakes reasonable efforts to operate secure data networks
          which are protected by industry-standard firewall and password
          protection systems. FELIX undertakes reasonable efforts to review its
          security and privacy policies on a periodic basis and it may adjust
          and change the systems as necessary. Notwithstanding the above, and
          although FELIX is ever diligent in its security pursuits, it cannot
          guarantee the success of its efforts. FELIX undertakes no duty to
          provide notice to You of a security breach unless otherwise required
          to do so by law. FELIX hereby disclaims any and all liability for any
          breach of security that may or may not result in the sharing or
          dissemination of information collected from and/or provided by You.
          FELIX shall not be liable for damages of any kind including, without
          limitation, special, exemplary, punitive, indirect, direct,
          incidental, or consequential (including but not limited to lost
          profits or lost savings) and whether based in contract, tort,
          negligence, strict liability or otherwise, which arises out of or is
          in any way connected with FELIX’s collection of Your information, or
          the unintentional dissemination thereof.
        </p>

        <h2>SPECIAL CASES</h2>

        <p>
          It is FELIX’s policy to not use or share Your Personal Information in
          ways that have not been outlined or described herein without first
          allowing You a chance to opt-out or otherwise disallow such unrelated
          uses. However, FELIX may disclose Personal Information about You or
          information relating to Your use of the Website for any reason if, in
          its sole discretion, it determines that it is reasonable to do so
          including, without limitation:
        </p>

        <p>
          A. To comply with laws, such as the Electronic Communications Privacy
          Act, regulations, or governmental or legal requests for such
          information;
        </p>
        <p>
          B. To reveal information that is needed to identify, contact, or bring
          legal action against a user who may be violating the terms of use or
          any other policies of the Website and/or other agreements with FELIX;
        </p>
        <p>C. To operate the Website properly;</p>
        <p>D. To protect the Website and its users; and/or</p>
        <p>
          E. To fully cooperate with law enforcement authorities, private-party
          litigants and others seeking information about its users to the extent
          required by applicable law.
        </p>
        <h2>PROTECTION OF CHILDREN</h2>

        <p>
          FELIX does not knowingly collect or use any personal information from
          children (minors younger than 18) through the Website. If You are a
          parent and believe FELIX may have inadvertently collected such
          information from User’s child, please notify FELIX immediately by
          sending an email to contact@felixhomes.com.
        </p>

        <h2>ADDITIONAL INFORMATION</h2>

        <p>
          If You have any questions about this Privacy Policy, please feel free
          to contact FELIX via email at contact@felixhomes.com.
        </p>
        <h2>FELIX TRANSFERS OF INFORMATION</h2>
        <p>
          Information about You including, without limitation, the Anonymous
          Information and/or Personal Information, may be disclosed in
          association with certain business dealings such as any debt financing,
          acquisition or merger, sale of assets, and in the event of a
          bankruptcy, assignment for benefit of creditors or receivership in
          which particular information could be sold or transferred to other
          parties as an asset. By accessing, viewing, and/or using the Website
          and/or any of the services offered by FELIX, You consents to the
          Website’s use of Your information as outlined in this Privacy Policy.
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
